### ISSUE TITLE
ValueError: 9: An unexpected error occurred

### ISSUE THREAD

**Issue by s4w3d0ff** [02strich/python-pandora#14]
``` python
>>> box = pandora.pandora.Pandora()
>>> box.user = 'myemail@email.com'
>>> box.update_station_list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandora/pandora.py", line 10, in check_authentication
    return f(self, *args)
  File "pandora/pandora.py", line 35, in update_station_list
    self.stations = self.connection.get_stations(self.user)
  File "pandora/connection.py", line 63, in get_stations
    return self.do_request('user.getStationList', False, True, user)['stations']
  File "pandora/connection.py", line 130, in do_request
    raise ValueError("%d: %s" % (code, msg))
ValueError: 9: An unexpected error occurred
>>> box.user = None
>>> box.update_station_list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandora/pandora.py", line 9, in check_authentication
    raise ValueError("User not yet authenticated")
ValueError: User not yet authenticated
>>> 
```

I don't quite understand how this module works. And I can't seem to find the documentation so I have been attempting to read the model source but obviously failing.

Do I need to specify a "box.password"?

**Comment by 02strich** [comment]
Hey,

thanks for looking into this. Please have a look at https://github.com/02strich/python-pandora/blob/master/pandora/__main__.py for details on how to use it.

**Comment by s4w3d0ff** [comment]
That helps thank you
