### ISSUE TITLE
Error while getting stations

### ISSUE THREAD

**Issue by krikunts** [02strich/python-pandora#3]
I've get some strange answer from pandora while getting list of stations.

Here is stacktrace:

Traceback (most recent call last):
  File "pandora_test.py", line 11, in <module>
    stations = pandora.get_station_list()
  File "/usr/local/lib/python2.7/dist-packages/pandora/pandora.py", line 18, in get_station_list
    return self.connection.get_stations()
  File "/usr/local/lib/python2.7/dist-packages/pandora/connection.py", line 60, in get_stations
    return self.do_request('user.getStationList', False, True)['stations']
  File "/usr/local/lib/python2.7/dist-packages/pandora/connection.py", line 108, in do_request
    raise ValueError("%d: %s" % (code, msg))
ValueError: 12: An unexpected error occurred

But if I use returnStationList parameter in auth.userLogin method stations are getting correctly. So I've patched your conection.py for myself to save the station list during authenticate method and return it in get_stations method. I hope this can be useful somehow

**Comment by 02strich** [comment]
Thanks for the report and the fix
