### ISSUE TITLE
Issue with switch_station function

### ISSUE THREAD

**Issue by Gh0stWires** [02strich/python-pandora#6]
When I try to run the switch_station function it give me this error

Traceback (most recent call last):
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\anarchyRadio.py", line 16, in <module>
    main()
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\anarchyRadio.py", line 12, in main
    pan.switch_station(pan.stations[3])
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\pandora.py", line 10, in check_authentication
    return f(self, *args)
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\pandora.py", line 70, in switch_station
    self.backlog = self.connection.get_fragment(self.user, self.current_station) + self.backlog
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\connection.py", line 64, in get_fragment
    return self.do_request('station.getPlaylist', True, True, user, stationToken=station['stationToken'])['items']
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\connection.py", line 122, in do_request
    raise ValueError("%d: %s" % (code, msg))
ValueError: 1003: An unexpected error occurred

**Comment by 02strich** [comment]
Hi,

can you please post your code? I just tried with the demo code in pandora.py and it worked for me.

Thanks

**Comment by Gh0stWires** [comment]
I was running the pandora.py demo and got that same error. after i sign into a pandora account it returns a list of stations and then gives me this

Traceback (most recent call last):
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\pandora.py", line 115, in <module>
    pandora.switch_station(quickmix)
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\pandora.py", line 10, in check_authentication
    return f(self, *args)
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\pandora.py", line 70, in switch_station
    self.backlog = self.connection.get_fragment(self.user, self.current_station) + self.backlog
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\connection.py", line 64, in get_fragment
    return self.do_request('station.getPlaylist', True, True, user, stationToken=station['stationToken'])['items']
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\connection.py", line 122, in do_request
    raise ValueError("%d: %s" % (code, msg))
ValueError: 1003: An unexpected error occurred

**Comment by 02strich** [comment]
what kind of Pandora account do you have?

In order to get higher audio quality the default client authentication has been changed to use the one from the "Pandora One" app. If you do not have a Pandora One account, you might need to change that back in the connection.py (see http://pan-do-ra-api.wikia.com/wiki/Json/5/partners for usernames and passwords)

**Comment by Gh0stWires** [comment]
So if i don't have a one account what do i switch it back to?

**Comment by 02strich** [comment]
probably to the Android login as it is the most widely used one

**Comment by Gh0stWires** [comment]
ok, thank you for your help. this is a really awesome api.

**Comment by Gh0stWires** [comment]
ok I changed all of this in my connection.py. but now its falling to connect to pandora at all i don't even get a chance to login.

```
PROTOCOL_VERSION = '5'
RPC_URL = "://tuner.pandora.com/services/json/?"
DEVICE_MODEL = 'android-generic'
PARTNER_USERNAME = 'android'
PARTNER_PASSWORD = 'AC7IBG09A3DTSYM4R41UJWL07VLN8JI7'
```

**Comment by 02strich** [comment]
Could you post the stacktrace please?

**Comment by Gh0stWires** [comment]
sure

Traceback (most recent call last):
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\anarchyRadio.py", line 3, in <module>
    pan = Pandora()
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\pandora.py", line 21, in **init**
    self.connection = connection_class()
  File "C:\Users\Samuel\Desktop\python-pandora-master\pandora\connection.py", line 46, in **init**
    raise Exception("Establishing connection to Pandora failed")
Exception: Establishing connection to Pandora failed

**Comment by 02strich** [comment]
thanks, I am sorry to have missed something: when changing the partner login (like you did), one also needs to change the encryption keys in crypt.py. The matching ones can be found on the same page as the partner login

**Comment by Gh0stWires** [comment]
what line in in crypt do i change?

**Comment by 02strich** [comment]
201 and 202

**Comment by Gh0stWires** [comment]
Thank you it works now. Is there i way I can contact you if I have some questions about using the api?

**Comment by 02strich** [comment]
sure, just open an issue
